branch-defaults:
  default:
    environment: ${{ secrets.EB_ENVIRONMENT_NAME }}
global:
  application_name: ${{ secrets.EB_APPLICATION_NAME }}
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
